name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validar AZURE_CREDENTIALS
        run: |
          if [ -z "${{ secrets.AZURE_CREDENTIALS }}" ]; then
            echo "AZURE_CREDENTIALS no está definido."
            exit 1
          fi
          echo "${{ secrets.AZURE_CREDENTIALS }}" | jq empty || { echo "AZURE_CREDENTIALS no es un JSON válido."; exit 1; }

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

          
